version: "3"
services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                - NB_USER:jovyan
                - NB_UID:1000
        ports:
            - "${JUPYTER_PORT}:8888"
        volumes:
            - ./app:/home/jovyan
        entrypoint: "jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root --NotebookApp.token=''"
