version: "3"
services:
    app:
        build:
            context: ./
            dockerfile: dev.Dockerfile
            args:
                - NB_USER=jovyan
        ports:
            - "${JUPYTER_PORT}:8888"
        volumes:
            - ./app:/home/jovyan
        networks:
            - default
    docsify:
        build:
            context: ./
            dockerfile: docsify.Dockerfile
        volumes:
            - ./:/usr/src
        networks:
            - default
        ports:
            - "${DOCSIFY_PORT}:3000"
networks:
    default:
        external:
            name: testing-cin-network
