version: "3"
services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                - NB_USER:jovyan
                - NB_UID:1000
        ports:
            - "${JUPYTER_PORT}:8888"
        volumes:
            - ./app:/home/jovyan
        networks:
            - default
        entrypoint: "jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root --NotebookApp.token=''"
    docsify:

        build:
            context: ./
            dockerfile: docsify.Dockerfile
        volumes:
            - ./:/usr/src
        networks:
            - default
        ports:
            - "${DOCSIFY_PORT}:3000"
networks:
    default:
        external:
            name: testing-cin-network
